# Generated by Django 5.1.15 on 2026-04-09 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=50, unique=True)),
                ('sku', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('list_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('dealer_price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_a', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_b', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('standard_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('map_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_drop_ship', models.BooleanField(default=False)),
                ('is_kit', models.BooleanField(default=False)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductAnnex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=10)),
                ('upc_code', models.CharField(blank=True, default='', max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annex', to='products.product')),
            ],
            options={
                'verbose_name': 'product annex',
                'verbose_name_plural': 'product annexes',
            },
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_kit', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_kits', to='products.product')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.product')),
            ],
            options={
                'unique_together': {('parent_product', 'component_product')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(choices=[('NY', 'New York'), ('FL', 'Florida'), ('D', 'Drop Ship'), ('OH', 'Ohio')], max_length=10)),
                ('on_hand_qty', models.IntegerField(default=0)),
                ('standard_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('mtd_units', models.IntegerField(default=0)),
                ('mtd_dollars', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ytd_units', models.IntegerField(default=0)),
                ('ytd_dollars', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory', to='products.product')),
            ],
            options={
                'verbose_name': 'warehouse inventory',
                'verbose_name_plural': 'warehouse inventory',
                'unique_together': {('product', 'warehouse_code')},
            },
        ),
    ]
