# Generated by Django 5.1.15 on 2026-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_code',
            field=models.CharField(blank=True, default='', help_text='Manufacturers Direct price code (from PRICE.CODES)', max_length=20),
        ),
    ]
