# Generated by Django 5.1.15 on 2026-04-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_expand_queue_choices'),
        ('products', '0002_add_pricing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=10)),
                ('committed_qty', models.IntegerField(default=0, help_text='Quantity allocated from on-hand')),
                ('backorder_qty', models.IntegerField(default=0, help_text='Quantity awaiting stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commitment', to='orders.orderline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='products.product')),
            ],
            options={
                'verbose_name': 'inventory commitment',
            },
        ),
    ]
