# Generated by Django 5.1.15 on 2026-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_full_order_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='queue_status',
            field=models.CharField(choices=[('OEQ', 'Order Entry'), ('MGQ', 'Management'), ('CHQ', 'Credit Hold'), ('PTQ', 'Pick Ticket'), ('IVQ', 'Invoice'), ('FQQ', 'Freight Quote'), ('CRDQ', 'Credit Card'), ('SRQ', 'Sales Review'), ('BOQ', 'Backorder'), ('PDQ', 'Price Discrepancy'), ('PQ', 'Problem'), ('CSQ', 'Customer Service')], default='OEQ', max_length=10),
        ),
    ]
