# Generated by Django 5.1.15 on 2026-04-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_gross_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('last_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('last_net_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('quote_gross_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quote_net_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('quote_comment', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'verbose_name': 'customer price history',
                'verbose_name_plural': 'customer price histories',
                'unique_together': {('customer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CustomerSpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('discount_1', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('net_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'customer special price',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
