# Generated by Django 5.1.15 on 2026-04-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('products', '0002_add_pricing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_code', models.CharField(max_length=50)),
                ('price_level', models.CharField(blank=True, default='', help_text='Override: L=List, A=Price A, B=Price B', max_length=5)),
                ('gross_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('discount_1', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_2', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('net_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'affiliation price',
                'unique_together': {('affiliation_code', 'product')},
            },
        ),
    ]
