# Generated by Django 5.1.15 on 2026-04-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('attention', models.CharField(blank=True, default='', max_length=200)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('fax', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('terms_code', models.CharField(blank=True, default='', max_length=20)),
                ('freight_terms', models.CharField(blank=True, default='', max_length=20)),
                ('resale_number', models.CharField(blank=True, default='', max_length=50)),
                ('affiliation', models.CharField(blank=True, default='', max_length=50)),
                ('salesman', models.CharField(blank=True, default='', max_length=50)),
                ('ar_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('open_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_code', models.CharField(blank=True, default='', max_length=5)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('over_90_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ytd_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('territory_1', models.CharField(blank=True, default='', max_length=20)),
                ('territory_2', models.CharField(blank=True, default='', max_length=20)),
                ('territory_3', models.CharField(blank=True, default='', max_length=20)),
                ('backorder_flag', models.BooleanField(default=False)),
                ('default_ship_via', models.CharField(blank=True, default='', max_length=50)),
                ('special_discounts', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'customers',
                'ordering': ['customer_number'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAnnex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictive_picking', models.BooleanField(default=False)),
                ('split_processing', models.BooleanField(default=False)),
                ('upc_exception', models.BooleanField(default=False)),
                ('route_to_ptq', models.BooleanField(default=False)),
                ('international_flag', models.BooleanField(default=False)),
                ('web_email', models.EmailField(blank=True, default='', max_length=254)),
                ('inventory_adjustment_pct', models.IntegerField(blank=True, null=True)),
                ('auto_label', models.BooleanField(default=False)),
                ('deferred_po', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annex', to='customers.customer')),
            ],
            options={
                'verbose_name': 'customer annex',
                'verbose_name_plural': 'customer annexes',
            },
        ),
    ]
