# Generated by Django 5.1.15 on 2026-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_code',
            field=models.CharField(choices=[('F', 'Fabrication (Default)'), ('B', 'BEST'), ('C', 'CLEO'), ('W', 'Whitely')], default='F', max_length=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='price_level',
            field=models.CharField(blank=True, default='', help_text='Override price level: L=List, A=Price A, B=Price B, X=BEST', max_length=5),
        ),
    ]
