# Generated by Django 5.1.15 on 2026-04-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("invoicing", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RMA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rma_number", models.CharField(max_length=20, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DEFECTIVE", "Defective"),
                            ("WRONG_ITEM", "Wrong Item Shipped"),
                            ("CUSTOMER_ERROR", "Customer Error"),
                            ("DAMAGE_TRANSIT", "Damaged in Transit"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RECEIVED", "Received"),
                            ("CREDITED", "Credited"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                ("issued_date", models.DateField()),
                ("received_date", models.DateField(blank=True, null=True)),
                ("credited_date", models.DateField(blank=True, null=True)),
                (
                    "restock_to_warehouse",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "credit_memo_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_by", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rmas",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rmas",
                        to="invoicing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "RMA",
                "verbose_name_plural": "RMAs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RMALine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                ("qty_returned", models.IntegerField(default=0)),
                ("qty_received", models.IntegerField(default=0)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "restock",
                    models.BooleanField(
                        default=True,
                        help_text="When received, add qty back to warehouse inventory",
                    ),
                ),
                (
                    "extension",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rma_lines",
                        to="invoicing.invoiceline",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rma_lines",
                        to="products.product",
                    ),
                ),
                (
                    "rma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="returns.rma",
                    ),
                ),
            ],
            options={
                "ordering": ["line_number"],
                "unique_together": {("rma", "line_number")},
            },
        ),
    ]
