# Generated by Django 5.1.15 on 2026-04-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_full_order_models"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20, unique=True)),
                ("warehouse_code", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PICKED", "Picked"),
                            ("PACKED", "Packed"),
                            ("SHIPPED", "Shipped"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("picked_at", models.DateTimeField(blank=True, null=True)),
                ("packed_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pick_ticket",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PickTicketLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                ("warehouse_code", models.CharField(max_length=10)),
                ("qty_ordered", models.IntegerField(default=0)),
                ("qty_picked", models.IntegerField(default=0)),
                (
                    "pick_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="fulfillment.pickticket",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pick_lines",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["line_number"],
                "unique_together": {("pick_ticket", "line_number")},
            },
        ),
    ]
