# Generated by Django 5.1.15 on 2026-04-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fulfillment", "0001_initial"),
        ("orders", "0002_full_order_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickticket",
            name="is_backorder",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pickticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pick_tickets",
                to="orders.order",
            ),
        ),
    ]
